### ISSUE TITLE
Outputs of the function cube.fit_lines_in_integrated_region()

### ISSUE THREAD

**Issue by marielougm** [thomasorb/orcs#1]
Hi, 

The results from the function cube.fit_lines_in_integrated_region() are given as a dictionary and the lines velocities for example are accompanied with their uncertainties. I was wandering how to transform these outputs as different arrays in order to plot the results with error bars for example.

Thank you!

-ML

**Comment by thomasorb** [comment]
Good question ! and welcome @marielougm 

Fitting functions return fitting parameters as three arrays. e.g. `'velocity'`, `'velocity_err'` and `'velocity_gvar'` or `'broadening'`, `'broadening_err'`, `'broadening_gvar'`. The first array is the mean value, the second the standard deviation (the error, or the uncerainty on the mean value), the third one is an array of Gaussian variables (gvar.GVar, see http://pythonhosted.org/gvar/). A Gaussian variable is a mean value and its standard deviation. A array of Gaussian variable can be converted to an array of mean values with the function `gvar.mean()` and an array of standard deviations with the function `gvar.sdev()`. Let's say that fit_results is the output of the fitting function, we have the following relations:
```python
fit_results['velocity'] = gvar.mean(fit_results['velocity_gvar'])
fit_results['velocity_err'] = gvar.sdev(fit_results['velocity_gvar'])
```
The same relations hold for `fit_results['broadening']`, `fit_results['flux']` and `fit_results['fitted_params']` ;)

If you now want to plot velocity wrt flux with error bars you can do the following

```python
pl.errorbar(fit_results['flux'], fit_results['velocity'], xerr=fit_results['flux_err'], yerr=fit_results['velocity_err'])
```

If you agree I consider this issue as closed ;)
