### ISSUE TITLE
ORB import error: no module named cutils / cgvar

### ISSUE THREAD

**Issue by thomasorb** [thomasorb/orcs#25]
This error can happen when `orb/cutils.pyx` or `orb/cgvar.pyx` has not been compiled. You can compile `orb/cutils.pyx` and `orb/cgvar.pyx` with this command in orb root folder:

`python setup.py build_ext --inplace`

**Comment by BLaunet** [comment]
This issue might be due to the fact that files ```orb/cutils.c```, ```orb/cutils.o``` and ```orb/cgvar.c``` (i.e compiled files) are present in orb repository. 
Deleting them would probably force the compilation from scratch at installation.
